### PR TITLE
feat: Add `id` field to each item

### PR DESCRIPTION
**Pull request by blaine-arcjet**
WIP

This PR adds an `id` field to each item. These will be useful for generating user-friendly variants and strings for each item. In doing so, users won't need to know about the specific Regex/pattern being used and we can make changes or improvements without affecting their code.

In doing this, I noticed a few things:
1. There are a LOT of dead links in this list. I think that if we saw a user agent from a dead project, that would indicate someone trying to work around a blocklist.
2. Some of the patterns are too generic. For example the `alexabot` pattern overlaps with `exabot` which is the wrong behavior.

We need to decide on how we name things. I also want to review some of my early decisions, as I changed my mind on some things as I was naming. For example:
a `-monitor` for things like pingdom
b. `-validate-*` for validators. Are link checkers just validators? Should they be named "-validate-links"?
c. Should scrapers vs crawlers be identified differently or is everything just a crawler?
d. Should we have a suffix for archivers?

### CODE REVIEW

**Comment by blaine-arcjet** [comment]
Near the end, I've also been using `-aggregate` for news aggregators.

**Comment by blaine-arcjet** [comment]
Since it's "crawler" and "feedfetcher", I think I need to use "validator" and "aggregator"

**Comment by blaine-arcjet** [comment]
> A scraper implies "bad" vs a "crawler" is good, but is that a user decision?

Most websites created for crawlers/spiders refer to them as either or both, even when they say they are a "good bot" (e.g. adhering to robots.txt)

**Comment by davidmytton** [comment]
IDs all make sense to me

**Comment by blaine-arcjet** [comment]
I think I'm going to change `vercel-monitor-screenshot` to `vercel-monitor-preview` because I think that user agent is for the preview image on the vercel dashboard.

**Review by e-moran — APPROVED** [review]

**Pull request merged**
